version: 2
jobs:
  build:
    working_directory: ~/docbook/defguide/en/defguide5
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        working_directory: ~/docbook/defguide/en/defguide5
        command: sudo add-apt-repository -y ppa:cwchien/gradle
    - run:
        working_directory: ~/docbook/defguide/en/defguide5
        command: sudo apt-get -y update
    - run:
        working_directory: ~/docbook/defguide/en/defguide5
        command: sudo apt-get -y install gradle
    - run:
        working_directory: ~/docbook/defguide/en/defguide5
        command: 'echo ''America/Chicago'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure
          -f noninteractive tzdata; sudo service mysql restart; sudo service postgresql
          restart; '
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: if [ -a ./gradlew ]; then gradlew dependencies; else gradle dependencies; fi
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.m2
        - ~/.ivy2
        - ~/.gradle
    - run: if [ -a ./gradlew ]; then gradlew test; else gradle test; fi
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
